import os
import pathlib
import pygame
from typing import Any
import datetime
import time

TITLE: str = "Vordocs"
VERSION: str = "0.0.4"
DEBUG: bool = True
LOGDOCS: bool = False
PARSEWARNINGS: bool = False

UISCALE: float = 1
FONT: str = "consolas"

class Colors:
    black = (0, 0, 0)
    background1 = (37, 37, 37, 255)
    background2 = (57, 57, 57, 255)
    text1 = (190, 190, 190, 255)
    text2 = (110, 110, 110, 255)
    textred = (150, 90, 90, 255)
    textgreen = (90, 150, 90, 255)
    textblue = (90, 90, 150, 255)
    hover1 = (255, 255, 255, 100)
    hover2 = (255, 255, 255, 50)


# MARK: File Manager
class FileManager:
    """
    The FileManager will automatically handle finding, parsing, and exporting markdown files.
    """

    possiblePaths: list[tuple[str, str]] = [
        (".", "../content"),   # "if Vordocs.py found in [0], then content is under [1]"
        ("generator", "content")
    ]

    def __init__(self):
        self.contentRoot: pathlib.Path = pathlib.Path()
        self.vorRoot: pathlib.Path = pathlib.Path()

        print("[FileManager] Searching for content root...")
        for possible in self.possiblePaths:
            if (pathlib.Path(possible[0]) / "Vordocs.py").is_file():
                self.vorRoot = pathlib.Path(possible[0])
                self.contentRoot = pathlib.Path(possible[1])
                break
        else:
            raise FileNotFoundError("[FileManager] Unable to find root!")

        print(f"[FileManager] Vordocs found at '{str(self.vorRoot)}'")
        print(f"[FileManager] Content found at '{str(self.contentRoot)}'")

    def getSymbol(self, name: str) -> pygame.Surface:
        return pygame.image.load(self.vorRoot / "symbols" / name).convert_alpha()
        


# MARK: Documentation
class Documentation:
    MODE_READONLY = 0
    MODE_EDIT = 1
    MODE_DEBUG = 2

    class DocData:
        ERROR_NONE = 0
        ERROR_EOF = 1

        ERROR_NOHEADER = 2
        ERROR_NOTITLE = 3
        ERROR_NODESC = 4


        class DocSection:
            class Item:
                PROPERTY = 0
                METHOD = 1
                EVENT = 2

                def __init__(self) -> None:
                    self.name: str = ""
                    self.type: int = self.PROPERTY
                    self.datatypes: list[Documentation.Item] = []
                    # ^ properties will only have 1 datatype and its what it is
                    # ^ functions will list inputs
                    # ^ events will list outputs
                    self.isVariadic: bool = False
                    self.description: str = ""


            def __init__(self) -> None:
                self.Name: str = "{section}"
                self.Items: list[Documentation.DocData.DocSection.Item] = []


        def __init__(self) -> None:
            self.parseError: int = self.ERROR_NONE

            self.Title: str = "{title}"
            self.Description: str = "{description}"

            # metadata
            self.Revision: int = 1
            self.RevisionText: str = "Generated by Vordocs on %r"   # time formatting
            self.RevisionOld: str = ""


            self.isStub: bool = True   # no summary (will not load further if no summary detected)

            # Summary
            self.summaryText: str = ""
            self.summarySections: list[Documentation.DocData.DocSection] = []

        def _incrementParseOffset(self, lines: list[Any], offset: int, error: bool = True) -> int:
            offset += 1
            if offset >= len(lines):
                if error: self.parseError = self.ERROR_EOF
                return -1
            return offset

        def _parseHeader(self, lines: list[str], offset: int) -> int:
            if LOGDOCS: print("[DOCUMENTATION] [PARSER] parsing header")
            # standard header is ---\ntitle: Part\ndescription: desc\n---

            while lines[offset].isspace():
                offset = self._incrementParseOffset(lines, offset)
                if (offset == -1):
                    return -1

            if lines[offset].strip("\n") != "---":
                self.parseError = self.ERROR_NOHEADER
                return -1
            
            offset = self._incrementParseOffset(lines, offset)
            if (offset == -1):
                return -1

            title: str = lines[offset]
            titlePrefix: str = "title: "
            if not title.startswith(titlePrefix):
                self.parseError = self.ERROR_NOTITLE
                return -1
            self.Title = title.removeprefix(titlePrefix).removesuffix("\n")

            offset = self._incrementParseOffset(lines, offset)
            if (offset == -1):
                return -1

            desc: str = lines[offset]
            descPrefix: str = "description: "
            if not desc.startswith(descPrefix):
                self.parseError = self.ERROR_NODESC
                return -1
            self.Description = desc.removeprefix(descPrefix).removesuffix("\n")

            offset = self._incrementParseOffset(lines, offset)
            if (offset == -1):
                return -1

            if lines[offset].strip("\n") != "---":
                self.parseError = self.ERROR_NOHEADER
                return -1

            return offset

        def _parseSummary(self, lines: list[str], offset: int) -> int:
            if LOGDOCS: print(f"[DOCUMENTATION] [PARSER] parsing summary ({offset})")
            while not lines[offset].startswith("## Summary"):
                offset = self._incrementParseOffset(lines, offset)
                if (offset == -1):
                    return -1

            offset = self._incrementParseOffset(lines, offset, error=False)
            if (offset == -1):
                return -1

            self.summaryText = lines[offset].strip("\n")

            self.isStub = False     # summary was found
            return offset

        def _parseSection(self, lines: list[str], offset: int, sections: list[Documentation.DocData.DocSection]) -> int:
            if LOGDOCS: print(f"[DOCUMENTATION] [PARSER] parsing next section ({offset})")

            while not lines[offset].startswith("## "):
                offset = self._incrementParseOffset(lines, offset, error=False)
                if (offset == -1):
                    if LOGDOCS: print("[DOCUMENTATION] [PARSER] no new section found")
                    return -1
                
            newSection = self.DocSection()
            newSection.Name = lines[offset].removeprefix("## ").removesuffix("\n")
            if LOGDOCS: print(f"[DOCUMENTATION] [PARSER] new section: {newSection.Name}")

            looking: bool = True
            while looking:
                newItem = self.DocSection.Item()
                
                if newSection.Name == "Properties":
                    newItem.type = self.DocSection.Item.PROPERTY
                elif newSection.Name == "Methods":
                    newItem.type = self.DocSection.Item.METHOD
                elif newSection.Name == "Events":
                    newItem.type = self.DocSection.Item.EVENT

                # find next item
                offset = self._incrementParseOffset(lines, offset)
                if (offset == -1):
                    break

                while not lines[offset].startswith("##"):
                    offset = self._incrementParseOffset(lines, offset, error=False)
                    if (offset == -1):
                        looking = False
                        break

                if lines[offset].startswith("## "):  # ran into next section
                    offset -= 1
                    break
            
                if not looking: # end of file (expected)
                    break

                newItem.name = lines[offset].removeprefix("### ").removesuffix("\n")

                newSection.Items.append(newItem)

            sections.append(newSection)
            return offset


        def parseFromFile(self, file: str):
            if LOGDOCS: print(f"[DOCUMENTATION] [PARSER] == BEGIN FILE @ {file} ==")

            f = open(file)
            lines: list[str] = f.readlines()
            f.close()

            offset = self._incrementParseOffset(lines, -1)
            if offset == -1: return
            offset = self._parseHeader(lines, offset)
            if offset == -1: return

            offset = self._incrementParseOffset(lines, offset)
            if offset == -1: return
            offset = self._parseSummary(lines, offset)
            if offset == -1: return

            offset = self._incrementParseOffset(lines, offset)
            while offset != -1:
                offset = self._parseSection(lines, offset, self.summarySections)



    class Item:
        FOLDER = 0
        CLASS = 1
        DATATYPE = 2
        GLOBAL = 3

        def __init__(self, itemType: int, name: str, filePath: str, data: Any | None = None) -> None:
            self.itemType: int = itemType
            self.Name: str = name
            self.filePath = filePath

            self.indent: int = 0
            self.index: int = 0

            self.children: list[Documentation.Item] = []
            self.Open: bool = False

            self.Rect: pygame.Rect = pygame.Rect(0, 0, 0, 0)

            if data is not None:
                self.Data: Documentation.DocData = data

            self.Scroll: int = 0
            self.maxScroll: int = 0
            self.maxY: float = 0

            # Rendering
            self.fontH1 = pygame.font.SysFont(FONT, int(36 * UISCALE))
            self.fontH2 = pygame.font.SysFont(FONT, int(30 * UISCALE))
            self.fontH3 = pygame.font.SysFont(FONT, int(24 * UISCALE))
            self.fontB = pygame.font.SysFont(FONT, int(16 * UISCALE))

        def draw(self, surface: pygame.Surface, x0: int, y0: int, w: int, h: int):
            if self.Data.parseError:
                text = "An Unknown Errro has Occursed"
                if self.Data.parseError == Documentation.DocData.ERROR_EOF:
                    text = "Unexpected EOF"
                elif self.Data.parseError == Documentation.DocData.ERROR_NOHEADER:
                    text = "No Header Found"
                elif self.Data.parseError == Documentation.DocData.ERROR_NOTITLE:
                    text = "No Title Found in Header"
                elif self.Data.parseError == Documentation.DocData.ERROR_NODESC:
                    text = "No Description Found in Header"

                text = pygame.font.SysFont(FONT, int(24 * UISCALE)).render(text, True, Colors.textred)
                surface.blit(text, (x0 + w / 2 - text.width / 2, y0 + h / 2 - text.height / 2))

                if not DEBUG:
                    return

            # if hasPreGeneratedUIElementsToSimplfiyEdittingMode: draw those
            # otherwise:

            x: float = x0 + 15 * UISCALE
            y: float = y0 + 15 * UISCALE + self.Scroll
            lineBreak: float = self.fontB.get_height()
            sectionSpaceSize: float = 30 * UISCALE
            indent: float = 10 * UISCALE

            t: pygame.Surface = self.fontH1.render(self.Data.Title, True, Colors.text1)
            surface.blit(t, (x, y))
            y += t.height

            t: pygame.Surface = self.fontB.render(self.Data.Description, True, Colors.text1)
            surface.blit(t, (x + indent, y))
            y += t.height

            # Summary
            y += sectionSpaceSize

            if self.Data.isStub:
                t: pygame.Surface = self.fontB.render("Stub", True, Colors.text2)
                surface.blit(t, (x, y))
                self.maxY = y
                return

            t: pygame.Surface = self.fontH2.render("Summary", True, Colors.text1)
            surface.blit(t, (x, y))
            y += t.height

            t: pygame.Surface = self.fontB.render(self.Data.summaryText, True, Colors.text1)
            surface.blit(t, (x + indent, y))
            y += t.height

            # Sections
            for section in self.Data.summarySections:
                y += sectionSpaceSize

                t: pygame.Surface = self.fontH2.render(section.Name, True, Colors.text1)
                surface.blit(t, (x, y))
                y += t.height

                for item in section.Items:
                    y += lineBreak

                    t: pygame.Surface = self.fontH3.render(item.name, True, Colors.text1)
                    surface.blit(t, (x + indent, y))
                    y += t.height
            
            self.maxY = y

    # MARK: Doc Init
    def __init__(self, fM: FileManager, win: Window, mode: int, windowWidth: int, windowHeight: int):
        self.mode: int = mode

        if (mode == self.MODE_EDIT):
            raise NotImplementedError("File Editting has not been implemented")

        self.Window: Window = win
        self.File: FileManager = fM

        self.x = 0
        self.y = 0
        self._scroll = 0

        self.idxSpacing = 20 * UISCALE
        self.indSpacing = 30 * UISCALE
        self.arrowSize = 20 * UISCALE
        self.iconSize = self.arrowSize

        self.ww = windowWidth
        self.wh = windowHeight

        self.explorerWidth = 400 * UISCALE

        self.font = pygame.font.SysFont(FONT, int(20 * UISCALE))

        self.mx, self.my = -100, -100

        # Build File Tree
        print("[Documentation] Building FileTree")
        self.Explorer: list[Documentation.Item] = []
        self.drawList: list[Documentation.Item] = []
        self.totalItems: int = 0

        self._expected = -1
        tree: list[str] = ["reference"]
    
        self.parseFolder(tree, self.Explorer)
        print(f"[Documentation] Scanned {self.totalItems} items")

        # Icons
        self.Icons: list[pygame.Surface] = [
            pygame.transform.scale(self.File.getSymbol("folder.png"), (self.iconSize, self.iconSize)),
            pygame.transform.scale(self.File.getSymbol("class.png"), (self.iconSize, self.iconSize)),
            pygame.transform.scale(self.File.getSymbol("datatype.png"), (self.iconSize, self.iconSize)),
            pygame.transform.scale(self.File.getSymbol("global.png"), (self.iconSize, self.iconSize)),
            pygame.transform.scale(self.File.getSymbol("generic.png"), (self.iconSize, self.iconSize)),
        ]
        self.arrowClosed = pygame.transform.scale(self.File.getSymbol("arrowClosed.png"), (self.arrowSize, self.arrowSize))
        self.arrowOpen = pygame.transform.scale(self.File.getSymbol("arrowOpen.png"), (self.arrowSize, self.arrowSize))

        # Menus
        self.selectedItem: Documentation.Item | None = None

        self.update()

    def parseFolder(self, tree: list[str], parent: list[Item]):

        if self.mode == self.MODE_DEBUG:
            folder: str = str(self.File.vorRoot) + "/debug/content/" + "/".join(tree)
        else:
            folder: str = str(self.File.contentRoot) + "/" + "/".join(tree)

        if self._expected == -1:
            self.Window.setWindowLoadingProgress("Loading Documentation...", 0)
            self._expected = sum(len(f) for _, _, f in os.walk(folder))

        docFolder: Documentation.Item = self.Item(self.Item.FOLDER, tree[-1], folder)
        parent.append(docFolder)

        for item in os.listdir(folder):
            path = pathlib.Path(folder + "/" + item)

            if path.is_dir():
                tree.append(item)
                self.parseFolder(tree, docFolder.children)
                tree.pop(-1)
            else:
                self.parseItem(item, str(path), docFolder)

    def parseItem(self, name: str, path: str, parent: Item):
        itemType = -1

        if parent.Name == "classes":
            itemType = self.Item.CLASS
        elif parent.Name == "datatypes":
            itemType = self.Item.DATATYPE
        elif parent.Name == "globals":
            itemType = self.Item.GLOBAL

        itemData: Documentation.DocData = self.DocData()
        itemData.parseFromFile(path)

        if itemData.parseError and PARSEWARNINGS:
            print(f"[Documentation] [Parser] Unable to parse {name} (err{itemData.parseError})")


        newItem: Documentation.Item = self.Item(itemType, name, path, data=itemData)
        parent.children.append(newItem)

        self.totalItems += 1
        #print(self.totalItems, "/", self._expected)
        self.Window.setWindowLoadingProgress("Loading Documentation...", self.totalItems / self._expected)

    def _update(self, idx: int, idn: int, item: Item) -> int:
        item.index = idx
        item.indent = idn
        self.drawList.append(item)

        idx += 1

        if item.Open:
            idn += 1

            for child in item.children:
                idx = self._update(idx, idn, child)

            idn -= 1

        return idx

    def update(self):
        self.drawList.clear()
        self._update(0, 0, self.Explorer[0])

    def draw(self, surface: pygame.Surface):
        self._scroll = max(self._scroll, self.getScrollMax())
        self._scroll = min(self._scroll, 0)

        pygame.draw.rect(
            surface,
            Colors.background2,
            (self.x, self.y, self.explorerWidth, self.wh)
        )

        for item in self.drawList:
            x = self.x + item.indent * self.indSpacing
            y = self.y + item.index * self.idxSpacing + self._scroll

            x0 = x

            if (len(item.children) > 0):
                img = self.arrowOpen if item.Open else self.arrowClosed
                surface.blit(img, (x, y))

            x += self.arrowSize
            surface.blit(self.Icons[item.itemType], (x, y))

            x += self.iconSize
            text: pygame.Surface = self.font.render(item.Name, True, Colors.text1)
            surface.blit(text, (x, y))

            item.Rect.x = x0
            item.Rect.y = y
            item.Rect.w = self.explorerWidth - x0
            item.Rect.h = self.iconSize

            if item.Rect.collidepoint(self.mx, self.my):
                temp = pygame.Surface((item.Rect.w, item.Rect.h), pygame.SRCALPHA)
                pygame.draw.rect(temp, Colors.hover1, temp.get_rect(), border_radius=10)
                surface.blit(temp, (item.Rect.x, item.Rect.y))
                # temp is required for transparency

            if item is self.selectedItem:
                temp = pygame.Surface((item.Rect.w, item.Rect.h), pygame.SRCALPHA)
                pygame.draw.rect(temp, Colors.hover2, temp.get_rect(), border_radius=10)
                surface.blit(temp, (item.Rect.x, item.Rect.y))

        if self.selectedItem is not None:
            self.selectedItem.draw(surface, 
                int(self.explorerWidth), 0, int(self.ww - self.explorerWidth), self.wh)

    def mouse(self, x: int, y: int, click: bool, isRight: bool = False):
        self.mx = x
        self.my = y

        if x > self.explorerWidth:
            return

        if not click:
            return

        for item in self.drawList:
            if not item.Rect.collidepoint(self.mx, self.my):
                continue

            if item.itemType == self.Item.FOLDER:
                item.Open = not item.Open
            else:
                self.selectedItem = item

            break
        else:
            self.selectedItem = None

        self.update()

    def scroll(self, scrollAmount: int):
        self._scroll += scrollAmount

    def getScrollMax(self) -> int:
        return -int(max(self.idxSpacing * len(self.drawList) - self.wh, 0))



# MARK: Window
class Window:
    def __init__(self, width: int, height: int):
        self.File: FileManager = FileManager()

        # Variables
        self.width: int = width
        self.height: int = height

        self.running = True
        self.mx, self.my = -100, -100

        # Pygame
        self.window: pygame.Surface = pygame.display.set_mode((width, height))
        self.clock: pygame.time.Clock = pygame.time.Clock()
        pygame.display.set_caption(self.getWindowTitle())
        pygame.display.set_icon(self.File.getSymbol("logo.png"))

        # Pygame Variables
        self.ExplorerSurface: pygame.Surface = pygame.Surface((width, height), pygame.SRCALPHA)
        self.labelFont = pygame.font.SysFont(FONT, int(32 * UISCALE))

        # Objects
        launchMode: int = Documentation.MODE_READONLY
        if DEBUG: launchMode = Documentation.MODE_DEBUG
        self.Docs: Documentation = Documentation(self.File, self, launchMode, self.width, self.height)

    def handleEvents(self):
        self.mx, self.my = pygame.mouse.get_pos()
        keys = pygame.key.get_pressed()

        self.Docs.mouse(self.mx, self.my, False)

        for e in pygame.event.get():
            if e.type == pygame.QUIT:
                self.running = False
            elif e.type == pygame.MOUSEBUTTONDOWN:
                if e.button == pygame.BUTTON_LEFT:
                    self.Docs.mouse(self.mx, self.my, True)
                elif e.button == pygame.BUTTON_RIGHT:
                    self.Docs.mouse(self.mx, self.my, True, isRight=True)
            elif e.type == pygame.MOUSEWHEEL:
                self.Docs.scroll(e.y * 30)

    def step(self):
        self.ExplorerSurface.fill(Colors.background1)
        self.handleEvents()

        self.Docs.draw(self.ExplorerSurface)

        self.window.fill(Colors.black) # <--
        self.window.blit(self.ExplorerSurface, (0, 0))

        pygame.display.flip()
        self.clock.tick(60)

    def setLabel(self, labelText: str):
        text: pygame.Surface = self.labelFont.render(labelText, True, Colors.text1)
        x = self.width / 2 - text.get_width() / 2
        y = self.height / 2 - text.get_height() / 2

        self.window.fill(Colors.background1)
        self.window.blit(text, (x, y))
        pygame.display.flip()

    def setWindowLoadingProgress(self, labelText: str, percent: float):
        text: pygame.Surface = self.labelFont.render(labelText, True, Colors.text1)
        x = self.width / 2 - text.get_width() / 2
        y = self.height / 2 - text.get_height() / 2

        bar0 = pygame.Rect(0, 0, self.width * 0.25, self.height * 0.01)
        bar0.center = (self.width / 2, self.height / 2 + self.height * 0.1)
        bar1 = pygame.Rect(bar0.x + bar0.w * 0.01 / 2,
                           bar0.y + bar0.h * 0.05 / 2,
                           bar0.w * percent * 0.99,
                           bar0.height * 0.95
        )

        self.window.fill(Colors.background1)
        self.window.blit(text, (x, y))
        pygame.draw.rect(self.window, Colors.black, bar0, border_radius=bar0.h)
        pygame.draw.rect(self.window, Colors.textgreen, bar1, border_radius=bar1.h)
        
        pygame.display.flip()


    def getWindowTitle(self) -> str:
        title: str = f"{TITLE} - v{VERSION}"
        if DEBUG:
            title += " - DEBUG MODE"
        return title


def main():
    pygame.display.init()
    pygame.font.init()

    w, h = pygame.display.get_desktop_sizes()[0]

    win = Window(int(w / 1.2), int(h / 1.2))

    while (win.running):
        win.step()

    pygame.quit()


if __name__ == "__main__":
    main()